---
title: "EDA - PS5"
output: html_document
---

You can also embed plots, for example:

# PS1: Price Histograms with Facet and Color
```{r, echo=FALSE}

# Create a histogram of diamond prices.
# Facet the histogram by diamond color
# and use cut to color the histogram bars.

# The plot should look something like this.
# http://i.imgur.com/b5xyrOu.jpg

# Note: In the link, a color palette of type
# 'qual' was used to color the histogram using
# scale_fill_brewer(type = 'qual')

# ENTER YOUR CODE BELOW THIS LINE
# ===========================================
summary(subset(diamonds,price > 1 && !is.na(price)))
ggplot(data = subset(diamonds,price > 1 && !is.na(price)),aes(x=price,fill = factor(cut)))+
  facet_wrap(~color,ncol = 3 )+
  geom_histogram()+
  scale_fill_brewer(type = 'qual') + scale_x_log10()

```

# PS1: Price vs. Table Colored by Cut
```{r, echo=FALSE}

# Create a scatterplot of diamond price vs.
# table and color the points by the cut of
# the diamond.

# The plot should look something like this.
# http://i.imgur.com/rQF9jQr.jpg


# ENTER YOUR CODE BELOW THIS LINE
# ===========================================
?diamonds #table: width of top of diamond relative to widest point (43–95)


ggplot(data = subset(diamonds,price > 1 && !is.na(price)),
       aes(x=table,y= price,
           color = factor(cut)))+
  geom_point()+
  scale_color_brewer(type = 'qual')+
  scale_x_continuous(lim = c(50,80), breaks = seq(50,80,2))
  

```

# Price vs. Volume and Diamond Clarity
```{r, echo=FALSE}
# Create a scatterplot of diamond price vs.
# volume (x * y * z) and color the points by
# the clarity of diamonds. Use scale on the y-axis
# to take the log10 of price. You should also
# omit the top 1% of diamond volumes from the plot.

# Note: Volume is a very rough approximation of
# a diamond's actual volume.

# The plot should look something like this.
# http://i.imgur.com/excUpea.jpg

# Note: In the link, a color palette of type
# 'div' was used to color the scatterplot using
# scale_color_brewer(type = 'div')

# ENTER YOUR CODE BELOW THIS LINE
# ===========================================
#table: width of top of diamond relative to widest point (43–95)
?mutate
?diamonds
diamonds<- mutate(diamonds,volume = x*y*z)

ggplot(data = subset(diamonds,price > 1 && !is.na(price)),
       aes(x=volume,y= price,
           color = factor(clarity)))+
  geom_point()+
    scale_y_log10() +
  scale_color_brewer(type = 'div')  +
    xlim(0, quantile(diamonds$volume, 0.99)) 
  #scale_x_continuous(lim = c(0,400), breaks = seq(0,400,50))
  

```

# Proportion of Friendships Initiated
```{r}
# Many interesting variables are derived from two or more others.
# For example, we might wonder how much of a person's network on
# a service like Facebook the user actively initiated. Two users
# with the same degree (or number of friends) might be very
# different if one initiated most of those connections on the
# service, while the other initiated very few. So it could be
# useful to consider this proportion of existing friendships that
# the user initiated. This might be a good predictor of how active
# a user is compared with their peers, or other traits, such as
# personality (i.e., is this person an extrovert?).

# Your task is to create a new variable called 'prop_initiated'
# in the Pseudo-Facebook data set. The variable should contain
# the proportion of friendships that the user initiated.

pf <- read.delim('pseudo_facebook.tsv')


# ENTER YOUR CODE BELOW THIS LINE
# ========================================================================
pf$prop_initiated = pf$friendships_initiated / pf$friend_count
pf$prop_initiated[is.na(pf$prop_initiated)] <- 0
pf$prop_initiated[is.infinite(pf$prop_initiated)] <- 0




summary(pf$prop_initiated)

```
# prop_initiated vs. tenure
```{r}
# Create a line graph of the median proportion of
# friendships initiated ('prop_initiated') vs.
# tenure and color the line segment by
# year_joined.bucket.

# Recall, we created year_joined.bucket in Lesson 5
# by first creating year_joined from the variable tenure.
# Then, we used the cut function on year_joined to create
# four bins or cohorts of users.

# (2004, 2009]
# (2009, 2011]
# (2011, 2012]
# (2012, 2014]

# The plot should look something like this.
# http://i.imgur.com/vNjPtDh.jpg
# OR this
# http://i.imgur.com/IBN1ufQ.jpg

# ENTER YOUR CODE BELOW THIS LINE
# ===========================================================
pf$year_joined <- 2014 - ceiling(pf$tenure / 365)
pf$year_joined.bucket = cut(pf$year_joined,c(2004,2009,2011,2012,2014))

ggplot(pf,aes(x = tenure,y = prop_initiated)) + geom_line(aes(color = year_joined.bucket) ,stat = 'summary', fun.y = 'median')

ggplot(pf,aes(x = tenure,y = prop_initiated)) + geom_line(aes(color = year_joined.bucket) ,stat = 'summary', fun.y = 'median')+geom_smooth()
```
#Largest Group Mean prop_initiated
```{r}
table(pf$year_joined.bucket)
by(pf$prop_initiated, pf$year_joined.bucket,summary)

```
# Price/Carat Binned, Faceted, & Colored

```{r}
# Create a scatter plot of the price/carat ratio
# of diamonds. The variable x should be
# assigned to cut. The points should be colored
# by diamond color, and the plot should be
# faceted by clarity.

# The plot should look something like this.
# http://i.imgur.com/YzbWkHT.jpg.

# Note: In the link, a color palette of type
# 'div' was used to color the histogram using
# scale_color_brewer(type = 'div')

# ENTER YOUR CODE BELOW THIS LINE
# ===========================================
?diamonds 
#cut: quality of the cut (Fair, Good, Very Good, Premium, Ideal)
#color: diamond colour, from J (worst) to D (best)
#clarity: (I1 (worst), SI1, SI2, VS1, VS2, VVS1, VVS2, IF (best))
ggplot(data = subset(diamonds,carat > 0 && !is.na(carat)),
       aes(x=cut,y= price/carat,
           color = factor(color)))+
  geom_jitter(alpha = 0.8)+ #scale_y_log10()+
  scale_color_brewer(type = 'div') + facet_wrap(~clarity)
  #scale_x_continuous(lim = c(50,80), breaks = seq(50,80,2))

```


```{r}
# The Gapminder website contains over 500 data sets with information about
# the world's population. Your task is to continue the investigation you did at the
# end of Problem Set 4 or you can start fresh and choose a different
# data set from Gapminder.

# If you’re feeling adventurous or want to try some data munging see if you can
# find a data set or scrape one from the web.

# In your investigation, examine 3 or more variables and create 2-5 plots that make
# use of the techniques from Lesson 5.

# You can find a link to the Gapminder website in the Instructor Notes.

# Once you've completed your investigation, create a post in the discussions that includes:
#       1. the variable(s) you investigated, your observations, and any summary statistics
#       2. snippets of code that created the plots
#       3. links to the images of your plots

# Copy and paste all of the code that you used for
# your investigation, and submit it when you are ready.
# ============================================================================================

library(ggplot2)
library(xlsx)
library(dplyr)
library(tidyr)
```



